### ISSUE TITLE
error occured when creating datalink channel using a dockerized masscanned

### ISSUE THREAD

**Issue by gfournel** [ivre/masscanned#138]
Hi there,
I encounter a problem with masscanned when trying to run it with Docker : when executing the masscanned command, it sysmetically gives this error message : 
 
thread 'main' panicked at 'An error occurred when creating the datalink channel: No such device (os error 19)', src/masscanned.rs:91:19

I use docker-compose version 2.18
network_mode: host
CAP_NET_RAW

Any idea?

Thanks a lot for your help

**Comment by p-l-** [comment]
You need to have the `CAP_NET_RAW` capability. Is it the case?

**Comment by gfournel** [comment]
By the way, I've got same error when trying to run the local example given here : 

https://github.com/ivre/masscanned#try-it-locally

**Comment by p-l-** [comment]
Do you have something in the kernel logs / `dmesg`?

**Comment by gfournel** [comment]
nothing in /var/log

**Comment by gfournel** [comment]
Finally, I updated my local version of masscanned and everything worked fine :)
I close this issue
