### ISSUE TITLE
(Applicative) protocols should be able to say whether they support TCP, UDP or both

### ISSUE THREAD

**Issue by p-l-** [ivre/masscanned#18]
Also, one (applicative) protocol should be able to transport another protocol, applicative or not.

This will be particularly helpful for protocols supporting both TCP and UDP with minor changes (e.g., the size is added at the beginning of the packet in TCP and not in UDP; both RPC and DNS, at least, do that).

The second part will also help for encapsulation, e.g.,VXLAN.

**Comment by Frky** [comment]
The L4 protocol information is set in the client_info structure:
```[Rust]
pub struct ClientInfo {
    pub mac: ClientInfoSrcDst<MacAddr>,
    pub ip: ClientInfoSrcDst<IpAddr>,
    pub transport: Option<IpNextHeaderProtocol>,
    pub port: ClientInfoSrcDst<u16>,
    pub cookie: Option<u32>,
}
```

For instance, in [ipv4.rs line 61](https://github.com/ivre/masscanned/blob/master/src/layer_3/ipv4.rs#L61):
```[Rust]
/* Fill client info with transport layer procotol */
client_info.transport = Some(ip_req.get_next_level_protocol());
```

Is it not enough to decide, at the beginning of the `repl` function of a given protocol, whether to continue or return `None`?

**Comment by p-l-** [comment]
Thanks!
