### ISSUE TITLE
Logging MAC broadcasts

### ISSUE THREAD

**Issue by Unactived** [ivre/masscanned#70]
Hello,

I would like to log ARP activity concerning a machine running masscanned, using masscanned.
By that I include ARP Requests who-has <IP of the machine> (assuming the machine sees it).

However, in my current setup, masscanned seems to detect those when the destination MAC is the unicast MAC of the machine, but not when it's a broadcast (I haven't tested multicast as of writing this).

About ARP handling, the README states that 
> `masscanned` anwsers to `ARP` requests, for requests that target an `IPv4` address that is handled by `masscanned` (i.e., an address that is in the IP address file given with option `-f`

So it doesn't talk about the frame. *(oh uh I guess typo at anwsers btw)*

About Ethernet handling, the README states that
> `masscanned` answers to `Ethernet` frames, if and only if the following requirements are met:
> 
> * the destination address of the frame should be handled by `masscanned`, which means:
>     
>     * `masscanned` own `MAC` address,
>     * the broadcast `MAC` address `ff:ff:ff:ff:ff:ff`,
>     * a multicast `MAC` address corresponding to one of the `IPv4` addresses handled by `masscanned` ([RFC 1112](https://datatracker.ietf.org/doc/html/rfc1112)),
>     * a multicast `MAC` address corresponding to one of the `IPv6` addresses handled by `masscanned` ;
> 
> * `EtherType` field is one of `ARP`, `IPv4` or `IPv6`.

My environment is a Debian 11 machine. I'm using the `arping` binary from the APT `iputils-arping` package (NOT from the `arping` package, which gives a close but different utility).

That binary's convention is to send its first packet as a MAC broadcast. It is stated in their manpage:
```
-b
           Send only MAC level broadcasts. Normally arping starts from sending broadcast, and switch to unicast after reply received.
```
And I can confirm it by running a `tcpdump -qen -i INTERFACE arp` along, with which I get:
```
ATTACKER_MAC   > ff:ff:ff:ff:ff:ff, ARP, length 42: Request who-has MASSCANNED_IP (ff:ff:ff:ff:ff:ff) tell ATTACKER_IP, length 28
MASSCANNED_MAC > ATTACKER_MAC,      ARP, length 42: Reply           MASSCANNED_IP is-at MASSCANNED_MAC,                 length 28
```

So the machine running masscanned is answering to the ARP requests, itself. It does so as long as it's up.

However masscanned doesn't seem to pickup on it (when it's a broadcast) though the asked IP is the IP it's assigned to respond for (and though it does when the MAC is unicast).

It doesn't appear in `eth` either. There's just nothing.

That means another machine can just run `arping -f`, `arping -c 1` or `arping -b` against the machine IP and I won't know about it, which is rather frustrating.

I'm unsure if this is 
1. some sort of race condition : the system handling and clearing the request too fast for masscanned to see?
2. similarly, these things maybe staying in kernel space, never for a user space application like masscanned to see
3. a bug/untreated case on masscanned's part / in its dependencies
4. something peculiar about my setup I haven't considered, and didn't see doc about how it could be a problem

For 1. , I tried doing `arptables -P INPUT DROP`, i.e. setting the default policy to drop ARP requests (after accepting only some source IPs, and not the one I run arping from). But it didn't change anything for that issue. The machine's still answering and it's still not masscanned.

My motivation for that was that I'm doing the equivalent with iptables (DROP all INPUT in a specific interface) to "leave IP traffic to masscanned", and in that case it's working like a charm (instead of veth shenigans I don't understand and that'd make me lose the info of the original IP sender).

For 2. , I'm unsure of how I'd go about it. Ideally I'd send packets to user space in some way, and have masscanned pick them up normally in some way. `ebtables` (`ebtables-nft`) has a built-in `ulog` "thing" to pass the packets to a userspace daemon through "netlink multicast sockets", which I assume is generally [ulogd](https://www.netfilter.org/projects/ulogd/). And I have little idea what this all means. I guess if all else fails I could do something with `ebtables`' `log` "thing" that syslogs it instead, and forget about masscanned for that ARP edgecase.

Also I could probably be using `nft` itself directly but it seems daunting 😨 and also doesn't seem to accomodate ARP more than `ebtables-nft`.

For 3. , I haven't really looked into it, at first glance I don't really get how ARP is handled and thus it doesn't seem like a simple thing to look through.

4 is pretty clear in and of itself

I'm opening this issue to ask if you've encountered / thought about this, and maybe would have ideas how to go around it, similarly as to how there's a tutorial of one way to setup masscanned in a peculiar environment, making use of veths.

Sorry for the wall of text and keep in mind I know little about networking or Rust, and nothing about kernel thingies.

**Comment by Frky** [comment]
Hi,

Interesting question. I just rephrase it so we are sure I understood correctly the problem you are encountering:

> sometimes you send an ARP request to the machine hosting **masscanned**, you get an answer but this answer don't seem to be sent by **masscanned**.

Is that correct? If yes, is the IP assigned to the hosting computer? From what you wrote, I understand it is?

We never published the documentation about how to deploy **masscanned** (and we still should), but the way we use it, we do not assign the IP for **masscanned** to the host, so that we ensure that the kernel never answers packets for this IP address. Is it the configuration you are in?

Also, could you provide your `arptables` and `iptables` rules?

PS. Thanks for the typo.

**Comment by Unactived** [comment]
(read following comment first)

Hi,

First, indeed I am in the case where the IP is assigned to the hosting computer.

I don't really know how to simply rephrase-the-rephrasing so I'll just try and explain more clearly:
> All ARP requests for the IP of a machine hosting **masscanned** are all answered by the machine, possibly at kernel level.
> When **masscanned** is running and detects an ARP request for the IP of the machine, as it's told to impersonate it (ip-addr-file), it correctly answers.
> Thus, when **masscanned** is running and detects the requests, there are 2 ARP is-at responses for 1 ARP who-has request.

On its own, this wouldn't be an issue for me

Now,
> **masscanned** seems to *always* detect MAC Unicasts (the destination MAC, to whom the ARP request is sent, is that of the machine) and *never* detect MAC Broadcasts (the destination MAC is `ff:ff:ff:ff:ff:ff:ff:ff`).
>
> For example, on Debian 11 running `arping -b <IP_OF_MACHINE>` from another machine on the network, I receive the responses from the machine, but they aren't from **masscanned**, and indeed, **masscanned**'s output stays empty, no `eth` or `arp` is shown. (As earlier, `arping` is that of the `iputils-arping` package, see more detailed examples in first comment).

### **arptables** config : 

I've been running my tests with the base config (which gives:)
```
Chain INPUT (policy ACCEPT)

Chain OUTPUT (policy ACCEPT)
```
And with
```
arptables -A INPUT -s <IP_GATEWAY> -j ACCEPT
arptables -A INPUT -s <IP_B> -j ACCEPT
arptables -P INPUT DROP
```
and getting the same results. So from my experience and use of it, `arptables` does nothing for my problem. It must be doing its job though as I remember my ssh session eventually dropping when I did not give it the necessary exception before setting a drop policy.

(The 2 IP exceptions are on a different network than that the tests are in, and that network happens on a different network interface.)

### **iptables** config : 

Default config + Default Docker's own config + `iptables -A INPUT --in-interface $INTERFACE -j DROP` where `$INTERFACE` is the network interface studied by **masscanned**

### Example

- "target" is the machine running masscanned, "attacker" is another on a common network
- Using same `arping` binary
- Running `tcpdump -qen -i <INTERFACE> arp` on attacker
- Running `masscanned --iface <INTERFACE> --ip-addr-file ip_addresses` on target, ip_addresses containing target's assigned IP in the common network (haven't recompiled and switched to --ip-addr yet)
- Run `arping -c 2 -i 5 TARGET_IP` on attacker (2 packets, 5 second interval)

Note : the first packet will be a MAC broadcast, the second will be a MAC Unicast

Results : 

First ARP request : MAC broadcast

- no output in masscanned
- machine gives one is-at response (kernel)

Second ARP request : MAC Unicast

- masscanned detects and logs eth & arp, and sends an ARP reply
- machine gives two is-at responses (kernel & masscanned)

I actually might be able to afford to "unconfigure" the machine's IP on the interface (as I initially need it configured before using masscanned), but I did not find how to 😅

I tried doing `ip addr del IP/32 dev INTERFACE`, and putting interface down/up (I'm lost) but all that did is disable the kernel ARP responses to Unicasts. So, not kernel ARP responses to Broadcasts, and more importantly did not enable masscanned to detect Broadcast ARP requests.

I'd also need this change to persist across reboots that use cloud-config, and I can't dive into that for now.

**Comment by Unactived** [comment]
This is actually not a priority for me (that would rather be, say, #73).

Since my issue is mainly because I'm in a specifically abnormal setup (per masscanned standards) : having the IP configured for the host ;
feel free to not think about it too much and close the issue.

However if you happen to have ideas for it I'd still be interested.

**Comment by Frky** [comment]
Hi,

Sorry for the late reply. I tried to reproduce the apparent bug, unfortunately so far I failed.
What I did to try and reproduce:

1. Create a new network namespace and configure veth interfaces and IP addresses:
```
# ip netns add test
# ip link add vethtest type veth peer vethtest netns test
# ip addr add dev vethtest 10.99.99.1/24
# ip link set vethtest up
# ip netns exec vethtest ip addr add dev vethtest 10.99.99.2/24
# ip netns exec vethtest ip link set vethtest up
```

Like you, I gave the IP address that would be handled by **masscanned** to the interface (in my example, `10.99.99.2/24`).

2. Run **masscanned** in the other namespace:
```
# ip netns exec test masscanned -i vethtest --self-ip-list 10.99.99.2
```

3. With `arping` from `iputils-arping`:
```
arping -c 2 -i 5 -I vethtest 10.99.99.2
ARPING 10.99.99.2 from 10.99.99.1 vethtest
Unicast reply from 10.99.99.2 [3A:57:4F:B2:AD:4B]  0.554ms
Unicast reply from 10.99.99.2 [3A:57:4F:B2:AD:4B]  1.039ms
Unicast reply from 10.99.99.2 [3A:57:4F:B2:AD:4B]  0.577ms
Unicast reply from 10.99.99.2 [3A:57:4F:B2:AD:4B]  1.373ms
Sent 2 probes (1 broadcast(s))
Received 4 response(s)
```
There are two responses for each `ARP` probes, one from the kernel and one from **masscanned**. I also see that in the output of **masscanned**:
```
1688566864.245  eth     recv    02:f5:61:30:fc:77       ff:ff:ff:ff:ff:ff                                               Arp
1688566864.245  arp     recv    02:f5:61:30:fc:77       ff:ff:ff:ff:ff:ff       10.99.99.1      10.99.99.2      ArpOperation(1)
1688566864.245  arp     recv    02:f5:61:30:fc:77       ff:ff:ff:ff:ff:ff       10.99.99.1      10.99.99.2      ArpOperation(1)
1688566864.245  arp     send    02:f5:61:30:fc:77       3a:57:4f:b2:ad:4b       10.99.99.1      10.99.99.2      ArpOperation(2)
1688566864.245  arp     send    02:f5:61:30:fc:77       3a:57:4f:b2:ad:4b       10.99.99.1      10.99.99.2      ArpOperation(2)
1688566864.245  eth     send    02:f5:61:30:fc:77       ff:ff:ff:ff:ff:ff                                               Arp
1688566864.245  eth     recv    3a:57:4f:b2:ad:4b       02:f5:61:30:fc:77                                               Arp
1688566864.245  eth     drop    3a:57:4f:b2:ad:4b       02:f5:61:30:fc:77                                               Arp
1688566869.245  eth     recv    02:f5:61:30:fc:77       3a:57:4f:b2:ad:4b                                               Arp
1688566869.245  arp     recv    02:f5:61:30:fc:77       3a:57:4f:b2:ad:4b       10.99.99.1      10.99.99.2      ArpOperation(1)
1688566869.245  arp     recv    02:f5:61:30:fc:77       3a:57:4f:b2:ad:4b       10.99.99.1      10.99.99.2      ArpOperation(1)
1688566869.245  arp     send    02:f5:61:30:fc:77       3a:57:4f:b2:ad:4b       10.99.99.1      10.99.99.2      ArpOperation(2)
1688566869.245  arp     send    02:f5:61:30:fc:77       3a:57:4f:b2:ad:4b       10.99.99.1      10.99.99.2      ArpOperation(2)
1688566869.245  eth     send    02:f5:61:30:fc:77       3a:57:4f:b2:ad:4b                                               Arp
1688566869.245  eth     recv    3a:57:4f:b2:ad:4b       02:f5:61:30:fc:77                                               Arp
1688566869.245  eth     drop    3a:57:4f:b2:ad:4b       02:f5:61:30:fc:77                                               Arp
```

4. Same result with `scapy` sending `ARP` requests for `10.99.99.2`, both to `L2 BROADCAST` and to the `MAC` address of the interface **masscanned** listens on.

Could you try the above and tell me if you have something different?

**Comment by Unactived** [comment]
Hello, thank you for taking interest in this issue again.

I haven't touched this problem in a while and I had forgotten I had an open issue about it when I eventually "fixed" it. I also currently don't have available the setup I was using at this point.

My original motivation was wanting to "see all about a given IP unicast address", which would have included ARP who-has requests for the MAC address associated to that IP unicast address (both being bound to a single simple network interface).

If I recall correctly, the problem was actually on my part, making use of the now `self-ip-file` or `self-ip-list` option to specify the unicast IP address **masscanned** should "look for". Specifying this unicast address and no other means specifying no IP broadcast / multicast address.

> `masscanned` answers to `ARP` requests, for requests that target an `IPv4` address that is handled by `masscanned` (i.e., an address that is in the IP address file given with option `-f`

Following this documented behaviour that I had even quoted, **masscanned** thus correctly didn't pick up any regular (read: not specially crafted with arping) `ARP` who-has request which all have a `ff:ff:ff:ff:ff:ff` target hardware address and a target protocol address of `0.0.0.0`, both *not* associated with the handled unicast address.

If I recall correctly, simply adding the broadcast IP address `255.255.255.255` made `masscanned` correctly log ARP who-has requests (though I guess it would have also logged a bit more too). Sorry for raising an issue based on a personal incomprehension, and for forgetting to come back to it once cleared.
